language: php
php:
    - '5.6'
    - '7.0'
    - '7.1'
install:
    composer install

script:
    - vendor/bin/phpunit --coverage-clover=coverage/report/coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)